mod = "mod4"
terminal = "kitty"
screenshot = "grim - | wl-copy"
browser = "firefox"
screenlock = "swaylock"
runner = "rofi -icon-theme candy-icons -show-icons -show run"
switcher = "rofi -icon-theme candy-icons -show-icons -show window"
