alias upgrade="yay -Syu"
alias %="fg"
alias uefi-update="fwupdmgr refresh --force && fwupdmgr update"
alias reset-waybar="killall -SIGUSR2 waybar"
alias cat="bat"
alias connect-pi="ssh michael@michael-raspberrypi.local"
